---
title: "Mental Health and COVID-19 Trends from New York Times Headlines"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    smooth_scroll: true
    source_code: embed
runtime: shiny 
---

Overview
==========
Column
-----

This interactive web app shows the New York Times's coverage of COVID-19 for TODAY and some of the emotions these articles may elicit just from the title. Please note that this is based off headlines only, not the content of the articles. Additionally, this is not an official COVID-19 webpage. This is a class assignment for a Data Science course. We are also not representing the New York Times. The data here is publicly available data from the New York Time's website. 

This app is the first step to showing how news coverage of COVID-19 may be impacting the public's mental health. It is especially important for news outlets to consider language to prevent poor mental health outcomes. It is equally important to note a major limitation to the approach of this app - the articles representing each of the three emotion categories are selected by the presence of a selected list of words. Thus, the selection process is prone to errors. For example, the word "stress" may appear in the headline, but the article could be about preventing stress; however, our algorithm is not fine-tuned enough to discriminate these contextual differences. Additionally, articles can appear in multiple emotion categories, which can be contradictory. Nevertheless, despite these limitations, these categorizations may provide insight into the effect of microsecond glances at news headlines on mental health. With the current patterns of technology use, in which, users scroll through endless articles, key words may catch their eyes, evoking some sort of emotion, as they continue to scroll past the article. These glances result in impressions of headlines without contextual insight, as our app may capture. Last, this is not a complete picture of all COVID-19-related coverage on New York Times's Today's paper. If the headlines do not contain, "pandemic", "corona", or "virus", our algorithm will not have detected them. 

We were hoping to make this a longitudinal dataset, such that you, the user, can see how the proportion of COVID-19 coverage and emotion categories change over time, but this is a work in progress. Additionally, if time permitted, we would have hoped to do a more thorough, scientifically-supported process of selecting words related to the emotion categories. For example, although we differentiated fear and anxiety, often times, these may go hand in hand for the same word. It would also have been ideal to expand the number of emotion categories, but for the time being, our categories may suffice, based off precursory trends for the New York Times. 

Our word selection is not at all extensive, but a good start to conducting these kind of analyses. Below you may find a list of our selected words for each emotion category:
Anxiety: anxiety, stress
Fear: shock, morality, dead, death, chaos, bomb, scramble, drastic, sick, ill, kill, worst, extreme, fear, fright
Positive: kind, support, compassion, help

Data
===========

Column
-----
```{r global, include=FALSE}
library(flexdashboard)
library(rvest)
library(dplyr)
library(tidyverse)
library(stringr)
library(DT)
library(plotly)
  nytimes <- read_html("https://www.nytimes.com/section/todayspaper")
  nyt_headlines <- nytimes %>%
    html_nodes(".css-l2vidh.e4e4i5l1") %>%
    html_text
  nyt_subheadlines <- nytimes %>%
    html_nodes(".css-195cszl.e1f68otr0") %>%
    html_text()
  nyt_headlines <- as.data.frame(nyt_headlines) 
  nyt_subheadlines <- as.data.frame(nyt_subheadlines)
  names(nyt_subheadlines)[names(nyt_subheadlines) == "nyt_subheadlines"] <- "nyt_headlines"
  headlines <- rbind(nyt_headlines, nyt_subheadlines)

  corona <- grep("[cC]orona|[vV]irus|[pP]andemic|[lL]ockdown|[Oo]utbreak|[sS]hut", headlines$nyt_headlines, value=TRUE)
  corona <- as.data.frame(corona)
  names(corona)[names(corona) == "corona"] <- "headlines"
  topics_anxiety <- grep("([aA]nxiety|[sS]tress)", corona$headlines, value=TRUE)
  topics_fear <- grep("([sS]hock|[mM]orality|[dD]ead|[dD]eath|[cC]haos|[bB]omb|[sS]cramble|[dD]rastic|[sS]ick|[iI]ll|[kK]ill|[wW]orst|[eE]xtreme|[fF]ear|[fF]right)", corona$headlines, value=TRUE)
  topics_positive <- grep("([kK]ind|[sS]upport|[Cc]ompassion|[hH]elp)", corona$headlines, value=TRUE)
  emotions <- c("topics_positive", "topics_fear", "topics_anxiety")
  percentCorona <- round(as.numeric(nrow(corona))/as.numeric(nrow(headlines))*100, 2)
  percentCoronaOutput <- paste(percentCorona,"%", sep="")
```

Column{.sidebar}
-----------------------------------------------------------------------

### Emotions conveyed in COVID-19-releated NY Times articles today
```{r, include = TRUE}
#here users can choose which of the three (anxiety, fear and positive) to see

selectInput("corona", label = "Types of emotion conveyed",
            choices = c(anxiety = "topics_anxiety", 
                        positive = "topics_positive", 
                        fear = "topics_fear"))
```

Column
-----
### COVID-19-related Articles on This Day

```{r}
mainPanel(width = 12,
  renderDataTable ({ 
  DT::datatable(corona, options = list(
    pageLength = 25
  ))
  
}))
```

Column
-----
### Percentage of NYT Articles Related to COVID-19

```{r} 
covid_percent <- percentCorona
valueBox(covid_percent, icon = "fa-percent")
```

### Emotions Related to COVID-19 Articles
```{r} 
#show different tables by these three categories or plots

    output$table <- DT::renderDataTable({
          data <- head(corona, n = input$maxrows)
          if (input$corona == "topics_anxiety") {
            data <- data[data$corona == input$topics_anxiety,]
          }
          else if (input$corona == "topics_positive") {
            data <- data[data$corona == input$topics_positive,]
          }
          else if (input$corona == "topics_fear") {
            data <- data[data$corona == input$topics_fear,]
          }
          data <- datatable(data) 
        }
        , options = list(bPaginate = FALSE)
    )


```